// try {
//   // 可能会导致错误的代码
//   console.g('d')
// } catch (err) {
//   // 在错误发生时怎么处理
//   console.log(err.name);
//   console.log(err.message);
// }
try {
  // 可能会导致错误的代码
  console.g('d')
} catch (err) {
  // 在错误发生时怎么处理
  console.log(err.name);
  console.log(err.message);
} finally {

}